<a href="https://colab.research.google.com/github/HimanshuSahoo/DATA-SCIENCE/blob/main/Confidence_Interval_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from scipy import stats
import pandas as pd
import numpy as np

In [ ]:
glaxo_df=pd.read_csv('glaxo_df.csv')


In [ ]:
glaxo_df_ci = stats.norm.interval(0.95,
loc = glaxo_df.gain.mean(),
scale = glaxo_df.gain.std())
print( 'Gain at 95% confidence interval is:', np.round(glaxo_df_ci, 4))

Gain at 95% confidence interval is: [-0.0258  0.0266]


In [ ]:
beml_df=pd.read_csv('beml_df.csv')

beml_df_ci = stats. norm.interval(0.95,
loc=beml_df.gain.mean(),
scale=beml_df.gain.std())

In [ ]:
stats. norm.interval(0.95,
loc= 1990,
scale=2833/np.sqrt(140))

(1520.721510546228, 2459.2784894537717)

In [ ]:
glaxo_df_ci = stats.norm.interval(0.95,
loc = glaxo_df.gain.mean(),
scale = glaxo_df.gain.std())
print( 'Gain at 95% confidence interval is:', np.round(glaxo_df_ci, 4))

Gain at 95% confidence interval is: [-0.0258  0.0266]


## Population Std Dev known

Endpoints of the range that contains alpha percent of the distribution
+ interval ( alpha, loc=0, scale=1 )

In [ ]:
stats.norm.interval(0.95,
loc = 0,
scale = 1)
np.round(conf_int)

array([-2.,  2.])

In [ ]:
# Get Z-Value
## For 95% Confidence
stats.norm.ppf(.975)

1.959963984540054

In [ ]:
conf_int = stats.norm.interval(0.95,
loc = 1990,
scale = 2500/np.sqrt(140))
np.round(conf_int,0)

array([1576., 2404.])

## Population Std Dev not known

### a. Using Z

In [ ]:
conf_int = stats.norm.interval(0.95,
loc = 1990,
scale = 2833/np.sqrt(140))
np.round(conf_int,0)

array([1521., 2459.])

### b. Using t

In [ ]:
# To get t-value
## For 95% Confidence
stats.t.ppf(0.975,df=139)

1.977177724476122

In [ ]:
conf_int_t = stats.t.interval( alpha=0.95, df=139, loc=1990, scale=2833/np.sqrt(140))
np.round(conf_int_t,0)

array([1517., 2463.])

### Finding p-values

In [ ]:
# p-value for t-statistic
stats.t.cdf(-2.375,17)

0.014791498962710226

In [ ]:
# p-value for z-statistic
stats.norm.cdf(-1.71)

0.0436329365240319